### PR TITLE
Synchronous tests

### PR DESCRIPTION
**Pull request by Sanjo**
I think its ready for release.

### Tests

* fiber-utils have full unit test coverage
* Cucumber wrapper code was only tested manually and with Letterpress it is E2E tested
* Cucumber hooks still need tests, but that is not part of this feature
* I have also tested it with Letterpress.

### Chaining with sync methods

Chaining still works for sync methods that don't return anything.

### CODE REVIEW

**Comment by Sanjo** [comment]
I will extract this into a separate package sync-webdriver, so we can use it in the xolvio:webdriver Meteor package.

**Comment by samhatoum** [comment]
Sounds good. Is the default for sync mode on again?

**Comment by Sanjo** [comment]
> Sounds good. Is the default for sync mode on again?

Yes. Since this will be the option that is preferred by most people this should be the default. I don't want to change the default in a later release. We provide clear instructions with the release, so it should be not a problem for anyone.

**Comment by Sanjo** [comment]
* [ ] Tweak Cucumber step definition stub generation (no callback)
* [ ] Test if callback.pending() is still working

**Pull request merged**
