### PR TITLE
update bump browser driver versions

### PR DESCRIPTION
**Pull request by dheerajbhaskar**
Especially chrome, since it has a bug "cannot get automation extension” error with chrome version: 57.0.2987.98; reference: http://stackoverflow.com/questions/42806169/cannot-get-automation-extension-error-with-chrome-version-57-0-2987-98

Latest versions sourced from: https://github.com/vvo/selenium-standalone/blob/master/lib/default-config.js

### CODE REVIEW

**Comment by danhounshell** [comment]
Also need to update chromedriver in package.json to 0.2.28

**Comment by thebarty** [comment]
Related to https://github.com/xolvio/chimp/issues/604
and https://github.com/danhounshell/chimp/commit/7a2e23804cf9a35d112ba1077a750243751d1ef8

**Comment by dheerajbhaskar** [comment]
I've increased the versions in package.json of both selenium-standalone and chromedriver. 

I've not done chimp development before, cloning chimp and running npm install is giving me an error in pre-publish script, can someone else check if everything is okay or point me to a guide with which I can setup the dev environment?

**Comment by lgandecki** [comment]
@dheerajbhaskar  Could you show us the error and also tell us your node/npm version?

**Comment by dheerajbhaskar** [comment]
I wasn't able to reproduce the error. Perhaps was an intermittent error due to network or something, didn't notice clearly, was working late in the night.
Node: v6.10.2
npm: v3.10.10

PFA the Screenshot of me running npm install and then finding the versions
Screenshot


PS: Sigh I got my message blocked when I replied via email. Not sure if it was because I'd an attachment or that I've a signature (some repeating message in each of my replies might get flagged?)

**Comment by rsshilli** [comment]
Any update here?  I want to turn `captureAllStepScreenshots` and/or `screenshotsOnError` and I can't because of this silly error:
```
[chimp][hooks] Error: unknown error: cannot get automation extension
```
I'd love it if this was updated.

**Pull request merged**
