### PR TITLE
Make chimp work with JDK10

### PR DESCRIPTION
**Pull request by joscha**
Fixes:
```
{ Error: Cannot define class using reflection
    at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
    at Request.self.callback (node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at Request.<anonymous> (node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:422:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  details: undefined,
  message: 'Cannot define class using reflection',
  type: 'RuntimeError',
  seleniumStack:
   { type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'Cannot define class using reflection' } }
Error: Cannot define class using reflection
    at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
    at Request.self.callback (node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at Request.<anonymous> (node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:422:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```
due to JDK 10.

See https://github.com/vvo/selenium-standalone/issues/369 and https://github.com/vvo/selenium-standalone/pull/371 and https://github.com/webdriverio/wdio-selenium-standalone-service/issues/47

### CODE REVIEW

**Comment by joscha** [comment]
cc @serceman

**Comment by joscha** [comment]
CI errors do not seem to be related:
```
ExpectationFailed: Expected 'The world’s leading software development platform · GitHub' to equal 'The world's leading software development platform · GitHub'.
```
?

**Comment by joscha** [comment]
@samhatoum any chance to get this in?

**Comment by joscha** [comment]
@samhatoum is chimp still maintained?

**Comment by samhatoum** [comment]
Thank you for this. Chimp 1.0 has not moved to Chimpy:
https://github.com/TheBrainFamily/chimpy/pulls

**Pull request closed without merging**
