### PR TITLE
Feature multiple meteor servers

### PR DESCRIPTION
**Pull request by ejfrancis**
see issue #545 

Allows multiple Meteor app servers to be controller via separate DDP connections.

## Interface
The previous way of using a single server still works fine
```bash
chimp --ddp=http://localhost:3005 -mocha --path=tests
```
```javascript
let result = server.call('someMethod');
```

But now if multiple DDP options are given you can access them individually
```bash
chimp --ddp=http://localhost:3005 --ddp=http://localhost:3007 --mocha --path=tests
```
```javascript
let servers;
beforeEach(() => {
  servers = {
    first: server.instances[0],
    second: server.instances[1]
  };
});
let result1 = servers.first.call('someMethod');
let result2 = servers.second.call('someMethod');
let result3 = server.call('someMethod');        // global.server points to instances[0] for backwards compatibility
```

## Changes
* ddp connections are stored in `process.env` via index, so now instead of `process.env['chimp.ddp']` they're stored as `process.env['chimp.ddp0']`, `process.env['chimp.ddp1']` etc
* `global.ddp` is still a DDP connection to the first server, but a property `.instances[]` is added to it which contains all DDP connections by index
   * example: 
```
global.ddp = {
   ...DDP connection to process.env['chimp.ddp0'],
   instances: [
     {  
          ...DDP connection to process.env['chimp.ddp0']
     },
     {
          ...DDP connection to process.env['chimp.ddp1']
      }
   ]
}
```

@samhatoum

### CODE REVIEW

**Comment by ejfrancis** [comment]
I'll be updating unit tests, just wanted to get this visible asap

**Comment by ejfrancis** [comment]
Alright unit tests updated and README

**Comment by samhatoum** [comment]
Thank you sooo much! This is awesome

**Comment by samhatoum** [comment]
@ejfrancis looks like your test failed in circle

**Comment by samhatoum** [comment]
👍 thank you, will release ASAP

**Comment by ejfrancis** [comment]
awesome! the chimp code was nice and simple to understand and modify

**Comment by samhatoum** [comment]
ah the magic of tests

**Pull request merged**
