### PR TITLE
allow cucumber `name` option to run specific scenarios

### LINKED ISSUE #638: Cannot run single scenario
It was possible to run a single scenario like so: 

```
chimp folder/file.feature:33
```

Which would cause the scenario at line 33 of the file `file.feature` to run.

After chimp 0.49 or similar (probably after a cucumber update) this no longer works and the whole feature file is always executed. Also tried setting the scenario name like `name="Some scenario" but It doesn't work either.

Can someone verify the problem and/or point me to an alternative to run scenarios from the command line? Thank you!

### PR DESCRIPTION
**Pull request by tiagolr**
fixes #638

### CODE REVIEW

**Comment by lgandecki** [comment]
cool, thanks!

**Comment by joscha** [comment]
this conflicts with `name` for saucelabs as described in https://chimp.readme.io/docs/using-saucelabs-browserstack-seleniumgrid - passing an arbitrary name for the saucelabs test will now instruct cucumber to run a test of the same name (which usually means your test suite will be empty). E.g. this change will regress for anyone using `--name` and basically empty their test suite on CI. Workaround is to put the `name` into the json file, however I think ideally this change would be reverted to not break upgraders from before `0.50.0`.

**Comment by joscha** [comment]
Looking at #638, reverting might not be the best option. Maybe change the `name` param for saucelabs and document that in the release notes?

**Comment by jboydensfdc** [comment]
@joscha how were you able to work around this?  You mentioned embedding the `name` in a json file.  To which json file are you referring?

**Comment by joscha** [comment]
> @joscha how were you able to work around this? You mentioned embedding the `name` in a json file. To which json file are you referring?

It's been a while, but I think I did at the time. I set it here: https://github.com/xolvio/chimp/blob/87f11b4cd5f70d91504b54448d6a30f5fa796103/src/bin/default.js#L44 (we have our own chimp config file that extends this one)

**Pull request merged**
