### PR TITLE
Update for Selenium driver 3.1.x+

### PR DESCRIPTION
**Pull request by billyvg**
Changed API for `-debug`, now requires a boolean arg

### CODE REVIEW

**Comment by lgandecki** [comment]
@billyvg do you think this wouldn't cause issues with older selenium drivers? Or should we not worry about them since with new installations of chimp we should get 3.1x+ selenium anyway?

**Comment by billyvg** [comment]
Sorry, this will cause issues with versions < 3.1. This was a hastily done PR, but main purpose was to document the issue with 3.1. I can make it compatible with older versions if you'd like.

**Comment by samhatoum** [comment]
that would be awesome @billyvg if you could

**Comment by billyvg** [comment]
I don't have the resources to work on this atm, sorry!

**Pull request closed without merging**
