### PR TITLE
adding type definitions so as to make this work with typescript

### LINKED ISSUE #537: add type definitions for chimp
#####  Expected behaviour
Running `npm install --save-dev @types/chimp` should add types so that one can use typescript for testing.

#####  Actual behaviour
chimp has no types in npm, so running
`npm install --save-dev @types/chimp` results in the following stack trace:

```
C:\my-home\AutomationProjects\WebdriverioProjects\chimp-nedb>npm install --save-dev @types/chimp
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe"
 "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "@types/chimp"

npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/@types%2fchimp
npm ERR! 404
npm ERR! 404  '@types/chimp' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\my-home\AutomationProjects\WebdriverioProjects\chimp-nedb\npm-debug.log

```

##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

1. npm init -y
2. npm install --save chimp //ideally types need to have come in with chimp itself
3. npm install --save-dev //error

#####  Version & tools:

* Chimp command line used: *The exact command you used*
`.\\node_modules\\.bin\\chimp.cmd ./chimp.js --watch` in `scripts` section in `package.json`; 

* Chimp config file: *Please provide a Gist if you use a config file*
https://gist.github.com/dheerajbhaskar/f6c798c74223bcb99bf69a41d1514bf6

* Chimp: *type `chimp -v`*
0.44.0

* Node.js: *type `node -v`*
v6.4.0

* Java: *type `java -version`*
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode)

* Operation system: *type `uname -v`*
windows 10 pro x64

#####  Console / Log Output

```
C:\my-home\AutomationProjects\WebdriverioProjects\chimp-nedb>npm install --save-dev @types/chimp
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe"
 "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "@types/chimp"

npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/@types%2fchimp
npm ERR! 404
npm ERR! 404  '@types/chimp' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\my-home\AutomationProjects\WebdriverioProjects\chimp-nedb\npm-debug.log

```

Please put long logs in a [Gist](https://gist.github.com/) and provide a link here.

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

### PR DESCRIPTION
**Pull request by dheerajbhaskar**
# adding type definitions so as to make this work with typescript

This would fix #537 

I''m following the guide at https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html to add types to a package

TODO (AFAIK)
- [x] add types as dependencies
- [ ] make changes to tsconfig.json to mention these types (I know the change to make, its mentioned in #537, I don't how to do that for a package which gets published, would need help here)

### CODE REVIEW

**Comment by dheerajbhaskar** [comment]
I'd need help with making the tsconfig.json change. The change I've tested is mentioned in #537. I'm not sure how to package a tsconfig.json while publishing a package. 

Where do I make the change, some guidance would be helpful

**Comment by dheerajbhaskar** [comment]
I think just adding at the root should work, how do I test that? Just publish a test package to npm? or just create a link to this modified chimp source in another project and check?

**Comment by samhatoum** [comment]
the latter should work, just use `npm link` from the chimp dir and run `npm run prepublish`, then from another project you can use `npm link chimp`

Also, most of the `.ts` files should be from other frameworks like webdriver.io / mocha / cucumber / jasmine. There's very little (if any) chimp specific language.

**Comment by dheerajbhaskar** [comment]
@samhatoum thanks will try that.

Chimp, I'm sure has very few `.ts` files, but I'd need to put a `tsconfig.json` to make the webdriverio and mocha types work. Do you think I can just put it in the root of the chimp folder and it will work?

**Comment by samhatoum** [comment]
I don't know, I despise `ts` so I never use it :) Happy to include it for those that do though. @Sanjo any thoughts?

**Comment by samhatoum** [comment]
Hey @dheerajbhaskar did you get any further with 
>  make changes to tsconfig.json to mention these types (I know the change to make, its mentioned in #537, I don't how to do that for a package which gets published, would need help here)

**Comment by dheerajbhaskar** [comment]
Hey @samhatoum, I'm using the procedure to get typescript working in my chimp projects. But, I've not come around to trying it on chimp itself. Haven't been able to make enough time for it. 

If you or anyone wants to try this out, I'm happy to make a video on how I got it working or answer a few comments /emails

**Comment by samhatoum** [comment]
Closing this due to inactivity. Let me know if you get some time to reopen

**Pull request closed without merging**
