### PR TITLE
Adds direct chromedriver functionality without Java

### LINKED ISSUE #460: Option to only download chromedriver without Java/Selenium
Currently phantomjs works with the `--webdriver` flag and does not require java to be downloaded. This is because Webdriver.io can talk directly to phantomjs using its ghostdriver bindings.

Chromedriver has the same option. We just need to make sure to download chromedriver only. I'm not sure if selenium-standalone will allow to do that without selenium.

Once this is done, it's a case of copying the mechanism that is used with `--browser=phantom`, but instead we could use `--browser=chromedriver`.

It's also worth noting that in a future release of chromedriver, they will be including the headless option which would make this browser the superior option for compatibility.

### PR DESCRIPTION
**Pull request by lucetius**
closes #460

### CODE REVIEW

**Comment by lgandecki** [comment]
Please don't merge yet. The guys will generalize the common parts of chromedriver.js and phantom.js to DRY the code up.

**Comment by samhatoum** [comment]
No need. [Use the rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)) :)

**Comment by lgandecki** [comment]
I'm not convinced in this case, did you take a look at both files? :)
But, obviously, the decision is yours!

**Comment by samhatoum** [comment]
it's fine. Next time we'll refactor. it's no big deal

**Pull request merged**
