### PR TITLE
Downgrading to cucumberjs 1.0.0

### PR DESCRIPTION
**Pull request by bsommardahl**

### CODE REVIEW

**Comment by bsommardahl** [comment]
@samhatoum I thought it would be easier, but it seems we need a copy of cucumberjs v1.2.0 in xolvio's org to point to. Not sure if downgrading like this is the best option.

**Comment by bsommardahl** [comment]
Trying with v1.0.0 but I honestly have no idea what it might break. :)

**Comment by bsommardahl** [comment]
Test timed out. Not sure what to do.

**Comment by yann-stepienik-cko** [comment]
+1 for this

**Comment by samhatoum** [comment]
Thanks @bsommardahl, let me have a play with this and figure it out. 

I'm closing this PR until I come up with a solution, will track the issue on #441

**Pull request closed without merging**
