### PR TITLE
Add multiremote support in browserstack manager

### PR DESCRIPTION
**Pull request by naiquevin**
* Added `multiremote` wrapper method
* Updated `killCurrentSession` method to mark all sessions associated
  with the first build as `completed`. (Earlier only the first session
  was being marked).

### CODE REVIEW

**Comment by naiquevin** [comment]
The build failed at `npm install` which seems to be unrelated.

**Comment by naiquevin** [comment]
Added another commit to ensure sessions of only the current build are killed, by comparing the name of the build (as specified in desiredCapabilities).

**Comment by seriallos** [comment]
Just want to note that the most recent commit in this PR fixes a major issue with using BrowserStack alongside multiple parallel builds. Two or more independent agents running BrowserStack have a high probability of stopping the incorrect build since it's just picking the first one from the list.

It also appears that `noSessionReuse` stopped working at some point (I'm unable to configure from CLI, env vars, or the chimp config) so there's on current workaround with the latest version of Chimp

So major thumbs up on this PR and am eagerly awaiting a release with these changes!

**Comment by seriallos** [comment]
Follow up, there are some bugs with this PR, at least for me.

I had to make some changes to get the various options and calls working properly.

Save `webdriverOptions` on the object (since these options contain the build info, not the session manager):

```javascript
BrowserStackSessionManager.prototype.remote = function (webdriverOptions, callback) {

  var self = this;

  log.debug('[chimp][browserstack-session-manager] creating webdriver remote ');
  var browser = this.webdriver.remote(webdriverOptions);
  self.webdriverOptions = webdriverOptions;

  callback(null, browser);
  return;
};
```

Use `webdriverOptions` and fix some `this/self` errors:

```javascript
BrowserStackSessionManager.prototype.killCurrentSession = function (callback) {

  var self = this;
  var wdOptions = self.webdriverOptions;
  var bstackOptions = self.options;
  const wdHubSession = 'http://' + wdOptions.host + ':' + wdOptions.port + '/wd/hub/session';

  var killSession = function (session) {
    request.del(wdHubSession + '/' + session.automation_session.hashed_id, function (wdError, wdResponse) {
      if (!wdError && wdResponse.statusCode === 200) {
        var options = {
          url: bstackOptions.browserStackUrl + '/automate/sessions/' + session.automation_session.hashed_id + '.json',
          method: 'PUT',
          json: true,
          body: {status: 'completed'}
        };
        request(options, function (error, response) {
          if (!error && response.statusCode === 200) {
            log.debug('[chimp][browserstack-session-manager]', 'stopped session');
            callback();
          } else {
            log.error('[chimp][browserstack-session-manager]', 'received error', error);
            callback(error);
          }
        });
      }
      else {
        log.error('[chimp][browserstack-session-manager]', 'received error', wdError);
        callback(wdError);
      }
    });
  };

  var findBuild = function (builds) {
    var currentBuildName = wdOptions.desiredCapabilities.build;
    if (currentBuildName) {
      return _.find(builds, function (b) {
        return b.automation_build.name === currentBuildName;
      });
    } else {
      return builds[0];
    }
  };

  self._getBuilds(function (err, builds) {
    if (builds && builds.length) {
      var build = findBuild(builds);
      log.debug('[chimp][browserstack-session-manager]', builds, build);
      var buildId = build.automation_build.hashed_id;
    }
    if (buildId !== '') {
      self._getSessions(buildId, function (err, sessions) {
        if (sessions && sessions.length) {
          sessions.forEach(killSession);
        }
      });
    }
  });
};
```

**Comment by naiquevin** [comment]
@seriallos I confirm that there's a bug in the callback to `this._getBuilds`, in the `if (buildId !== '')` block, the value of `this` is incorrect in that context. I'll push a fix for it. 

However, I didn't understand why `webdriverOptions` had to be saved on the object. The `options` obj that all session managers are initialized with does contain `host` and `port`. Am I missing something?

**Comment by seriallos** [comment]
From what I could tell in my own debugging, some of the data was split between `this.options` and the `webdriverOptions`. The `desiredCapabilities` was definitely not on `this.options` in my environment which is used in `self._getBuilds`.

**Comment by naiquevin** [comment]
@seriallos Read the SessionFactory code and it makes sense now. I'll test again and push the changes. Thanks.

**Comment by naiquevin** [comment]
Updated the PR with the fix for the above bug (thanks @seriallos!). I had clearly missed while testing earlier.

**Comment by wuthiago** [comment]
@naiquevin @seriallos is this related to running Chimp on Selenium Grid?

**Comment by seriallos** [comment]
Specifically on BrowserStack. Running multiple tests at the same time would result in one session often prematurely stopping a separate session.

**Comment by naiquevin** [comment]
@wuthiago: This PR is primarily for adding multiremote (multiple browser instances at a time) support for BrowserStack implementation of the Session manager. 

But it additionally also includes the fix for killing only specific sessions and not the current sessions in the end. So yes it is in a way related to Selenium Grid.

**Pull request merged**
