### PR TITLE
Issue 369 - Command line options

### PR DESCRIPTION
**Pull request by deanius**
WIP Just starting it off right now..

### CODE REVIEW

**Comment by samhatoum** [comment]
This would be an awesome help

**Comment by deanius** [comment]
Acceptance criteria: ??

**Comment by samhatoum** [comment]
I'm thinking we can add the help for each command inside [the default config file](https://github.com/xolvio/chimp/blob/master/src/bin/default.js), and then have the `--help` provide a list of options, then have --help <command>` show the specific command help.

Data structure wise, I'm open to suggestions. We could:

* OPTION A: For every config option in the `deafult.config`, we would have a matching `<command>Help` option. So for example:

  ```javascript
module.exports = {
  watch: false,
  watchHelp: 'Puts Chimp into watch mode. This means lorem ipsum dolor...',
  ...
```

* OPTION B: We create an object for each command, then have a function that to export only the configs. So for example:

  ```javascript
const configuration = {
};

module.exports = function getConfiguration() {
  // filter out all the help commands deeply using some underscore magic
};
```

Option A is simplest, but it would pollute the environment variable space since Chimp takes all the config vars and exposes them over environment variables like this `env.chimp[<config>]`. So we would have `env.chimp['watchHelp']` available. Not nice :)

Option B doesn't have the problem above, is just a little bit more complex.

Open to other options.

**Comment by samhatoum** [comment]
@deanius any thoughts?

**Comment by samhatoum** [comment]
Still up for this @deanius? :)

**Comment by deanius** [comment]
Dang Sam. I sheepishly say no, but I'd love to get someone on my team to take it on for their first OSS badge.

**Comment by samhatoum** [comment]
Haha, I get how it goes. It would be amazing to get someone from your team, I'd love the help and I can work with them if they make the time.

**Comment by samhatoum** [comment]
closing due to age

**Pull request closed without merging**
