### PR TITLE
[WIP] Posts results to Simian

### PR DESCRIPTION
**Pull request by Sanjo**

### CODE REVIEW

**Comment by Sanjo** [comment]
* I don't like that the simianHost also includes the path. A host doesn't include the path.
* Can you add this test please:
  When the API server responds with the error `{status: 'error', error: 'invalid accessToken'}` (status code 401) it shows the "invalid accessToken" error to the user

Otherwise it looks good to me.

**Comment by samhatoum** [comment]
* I can rename it to `resultEndpoint` and make it generic
* Yes

**Comment by Sanjo** [comment]
> I can rename it to resultEndpoint and make it generic

simianResultEndpoint works for me. I don't understand how you want to make it generic. The result format is specific to our API. The only usecase for this option for me is that we can use the development or staging environment for testing.

**Comment by samhatoum** [comment]
I mean make the name more generic, not the function

It is decided: `simianResultEndpoint`

**Pull request merged**
