### PR TITLE
Node 6.x support

### PR DESCRIPTION
**Pull request by gregorskii**
updated `chokidar` and `fs-extra` to remove segfault on node 6.2

### CODE REVIEW

**Comment by samhatoum** [comment]
@gregorskii we should probably bump the node.js version in the circle config

**Comment by gregorskii** [comment]
Looks like the tests timed out. Can you rerun?

**Comment by samhatoum** [comment]
@gregorskii the issue is that we need to bump up the node.js engine to 6.x in the circle.yml file

**Comment by gregorskii** [comment]
I did that here: https://github.com/Deutschla/chimp/commit/046dc0c97140c42ad8304d2485dfdf4c4bab66a4

I am seeing some issues locally with fibers on the updated version. But it required me to update it for it to run on 6.x. I can investigate it further this week.

**Comment by Sanjo** [comment]
There are still two dependencies that use an older version of graceful-fs (< 4). It's mocha and selenium-standalone. You can see it in the [full dependency tree of chimp](https://gist.github.com/Sanjo/1290ae214a5b86f8bafcbb0594c2733f).

**Comment by Sanjo** [comment]
I've updated both packages in the branch https://github.com/xolvio/chimp/tree/Deutschla-master. But there is still:

```
└─┬ selenium-standalone@5.1.0
  └─┬ unzip@0.1.11
    └─┬ fstream@0.1.31
      └── graceful-fs@3.0.8 
```

The problematic package is unzip. It is not maintained. A replacement could be https://github.com/thejoshwolfe/yauzl.

The build still fails: https://circleci.com/gh/xolvio/chimp/292.

**Comment by Sanjo** [comment]
I've updated selenium-standalone to remove the dependency to graceful-fs < 4 mentioned in my [previous comment](https://github.com/xolvio/chimp/pull/393#issuecomment-225114723).

The pull-request is still pending: https://github.com/vvo/selenium-standalone/pull/183.

Chimp has still problems with running the Cucumber tests in Chrome with Node 6. But that seems to not be related to graceful-fs. It stops at the selenium status request and never gets an answer. But this is out of scope of this pull-request.

**Comment by vampolo** [comment]
Is anybody working on this ? Can i do something to help ?

**Comment by samhatoum** [comment]
Thanks @vampolo, would appreciate the help.

Looks like the PR has been accepted on selenium-standalone. Could you please update the latest selenium and apply to this PR? When the tests pass on Circle, I'll gladly merge.

**Comment by Sanjo** [comment]
The selenium-standalone update was a patch release, so Chimp will already use the latest selenium-standalone with the fix. However running the tests with Node.js 6 still fails for another reason, that I haven't looked into yet.

@vampolo I'm not working on this. The latest version is: https://github.com/xolvio/chimp/tree/Deutschla-master. Next step is to debug, why Chimp does not succeed with Node.js 6.

**Comment by vampolo** [comment]
Did some work in integrating this pr with an update of *selenium-standalone* (a major version was already in anyway)

Cucumber tests seems to fail. or in my case just hang forever. I've enabled all the debug information i could do from `chimp.js` and i get

image

Seems that on cucumber it is not even able to start the browser somehow.... Any suggestion on where to look is appreciated. will look at this later today. for now, no chimp.js :(

**Comment by vampolo** [comment]
More hints:

image

**Comment by samhatoum** [comment]
I think this is the chrome issue that Sanjo is talking about. To verify, you can try with Firefox.

**Comment by vampolo** [comment]
Doesn't seem browser related, more cucumber related. in particular the cucumber-wrapper goes in infinite loop.

image

**Comment by danielbayerlein** [comment]
Node 6.2 support would be great. Can I help?

**Comment by danielbayerlein** [comment]
I can confirm the bug of @vampolo.

My code changes:

```diff
--- a/src/lib/selenium.js
+++ b/src/lib/selenium.js
@@ -32,7 +32,7 @@ function Selenium (options) {
       chrome: {
         // check for more recent versions of chrome driver here:
         // http://chromedriver.storage.googleapis.com/index.html
-        version: '2.21',
+        version: '2.22',
         arch: process.arch,
         baseURL: 'https://chromedriver.storage.googleapis.com',
       },

--- a/package.json
+++ b/package.json
@@ -84,7 +84,7 @@
     "request": "2.67.0",
     "requestretry": "1.5.0",
     "saucelabs": "~0.1.1",
-    "selenium-standalone": "sanjo/selenium-standalone#deprecated-graceful-fs",
+    "selenium-standalone": "^5.1.1",
     "underscore": "~1.8.3",
     "xolvio-ddp": "^0.12.0",
     "xolvio-jasmine-expect": "^1.0.0",
```

Run the test with debug output:

```
Running Chimp Cucumber specs in Chrome
[chimp] loaded /Users/danielbayerlein/Projects/chimp/chimp.js
[chimp] Chimp options are { watch: false,
  watchTags: '@focus',
  watchWithPolling: false,
  criticalSteps: null,
  criticalTag: '@critical',
  server: false,
  serverPort: 8060,
  serverHost: 'localhost',
  sync: true,
  offline: false,
  path: './features',
  format: 'pretty',
  tags: '~@ignore',
  singleSnippetPerFile: true,
  recommendedFilenameSeparator: '_',
  chai: false,
  screenshotsOnError: false,
  screenshotsPath: '.screenshots',
  captureAllStepScreenshots: false,
  saveScreenshotsToDisk: true,
  saveScreenshotsToReport: false,
  jsonOutput: null,
  compiler: 'js:/Users/danielbayerlein/Projects/chimp/dist/lib/babel-register.js',
  browser: 'chrome',
  platform: 'ANY',
  name: '',
  user: '',
  key: '',
  port: null,
  host: null,
  webdriverio:
   { desiredCapabilities: {},
     logLevel: 'silent',
     host: '127.0.0.1',
     port: 4444,
     path: '/wd/hub',
     baseUrl: null,
     coloredLogs: true,
     screenshotPath: null,
     waitforTimeout: 500,
     waitforInterval: 250 },
  noSessionReuse: false,
  simianResultEndPoint: 'api.simian.io/v1.0/result',
  simianAccessToken: false,
  simianResultBranch: null,
  simianRepositoryId: null,
  mocha: false,
  mochaTimeout: 60000,
  mochaReporter: 'spec',
  mochaSlow: 10000,
  jasmine: false,
  jasmineConfig:
   { specDir: '.',
     specFiles: [ '**/*@(_spec|-spec|Spec).@(js|jsx)' ],
     helpers: [ 'support/**/*.@(js|jsx)' ],
     stopSpecOnExpectationFailure: false,
     random: false },
  jasmineReporterConfig: {},
  ddp: false,
  phantom_w: 1280,
  phantom_h: 1024,
  phantom_ignoreSSLErrors: false,
  log: 'info',
  debug: false,
  seleniumDebug: false,
  debugCucumber: null,
  debugBrkCucumber: null,
  debugMocha: null,
  debugBrkMocha: null,
  webdriverLogLevel: false }

[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][selenium] Selenium object created
[chimp][selenium] Start
[chimp][selenium] Installing Selenium + drivers if needed

[chimp][selenium] hub can be seen at http://localhost:50308/wd/hub
[chimp][session-manager] options are { host: 'localhost',
  port: '50308',
  browser: 'chrome',
  deviceName: undefined }
[chimp][session-manager] created a new SessionManager { host: 'localhost',
  port: '50308',
  browser: 'chrome',
  deviceName: undefined }
[chimp][cucumber] Cucumber exec options are:  [ 'node',
  '/Users/danielbayerlein/Projects/chimp/node_modules/.bin/cucumber.js',
  './features',
  '-r',
  '/Users/danielbayerlein/Projects/chimp/dist/lib/chimp-helper.js',
  '-r',
  '/Users/danielbayerlein/Projects/chimp/dist/lib/cucumberjs/world.js',
  '-r',
  '/Users/danielbayerlein/Projects/chimp/dist/lib/cucumberjs/hooks.js',
  '-r',
  './features',
  '--tags',
  '~@cli',
  '--format',
  'pretty',
  '--compiler',
  'js:/Users/danielbayerlein/Projects/chimp/dist/lib/babel-register.js' ]
[chimp][cucumber] Running with [ 'node',
  '/Users/danielbayerlein/Projects/chimp/node_modules/.bin/cucumber.js',
  './features',
  '-r',
  '/Users/danielbayerlein/Projects/chimp/dist/lib/chimp-helper.js',
  '-r',
  '/Users/danielbayerlein/Projects/chimp/dist/lib/cucumberjs/world.js',
  '-r',
  '/Users/danielbayerlein/Projects/chimp/dist/lib/cucumberjs/hooks.js',
  '-r',
  './features',
  '--tags',
  '~@cli',
  '--format',
  'pretty',
  '--compiler',
  'js:/Users/danielbayerlein/Projects/chimp/dist/lib/babel-register.js' ]
[chimp][helper] Using the jasmine-expect assertion library
[chimp][hooks] Starting BeforeFeatures
[chimp][helper] getting browser
[chimp][session-manager-factory] options are { host: 'localhost',
  port: 50308,
  user: undefined,
  key: undefined,
  browser: 'chrome',
  deviceName: undefined }
[chimp][session-manager] options are { host: 'localhost',
  port: 50308,
  user: undefined,
  key: undefined,
  browser: 'chrome',
  deviceName: undefined }
[chimp][session-manager] created a new SessionManager { host: 'localhost',
  port: 50308,
  user: undefined,
  key: undefined,
  browser: 'chrome',
  deviceName: undefined }
[chimp][helper] webdriverioOptions are  {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","name":""},"logLevel":"silent","host":"localhost","port":50308,"path":"/wd/hub","baseUrl":null,"coloredLogs":true,"screenshotPath":null,"waitforTimeout":500,"waitforInterval":250,"sync":true}
[chimp][session-manager] creating webdriver remote
[chimp][session-manager] checking connection to selenium server
```

`checking connection to selenium server` is the latest output.

The process sleep at this point: https://github.com/xolvio/chimp/blob/master/dist/lib/session-manager.js#L105

@samhatoum , @Sanjo Any idea?

**Comment by samhatoum** [comment]
@danielbayerlein You see the line `http://localhost:50308/wd/hub`? That port is dynamic. If you keep an eye on it next time you run it, then try to go to that location, does it work? Are you able to start a browser from the UI?

**Comment by danielbayerlein** [comment]
@samhatoum Yes, the page works.

bildschirmfoto 2016-06-24 um 20 14 36

**Comment by samhatoum** [comment]
are you able to create a session using the button for Chrome?

**Comment by danielbayerlein** [comment]
@samhatoum Yes, I can create a session and a new instance of Chrome opens. `[chimp][session-manager] checking connection to selenium server` is still the latest output.

**Comment by gregorskii** [comment]
Further testing is showing that Cucumber is timing out the CircleCI builds. Merged everything from master into the forked branch.

**Pull request merged**
