### PR TITLE
feat: supports unions and adds validation for duplicate union and interface.

### PR DESCRIPTION
**Pull request by Bhavesh-Suvalaka**

### CODE REVIEW

**Review by jmvtrinidad — APPROVED** [review]

**Comment by Bhavesh-Suvalaka** [comment]
Hi @lgandecki, could you please review and merge this PR ?

**Comment by lgandecki** [comment]
This looks good, could you guys please explain what's the reasoning behind the extra validation for duplicates? Is this somehow related to the unions or did you guys realize this would be nice to have additionally? 
wouldn't graphql itself fail with duplicated types? @jmvtrinidad @Bhavesh-Suvalaka

**Comment by BhaveshSuvalaka** [comment]
Hi @lgandecki, when I was testing the unions I accidentally added two same union type in module's schema and as my GraphQL plugin wasn't working in IDE it didn't complain. It even didn't fail during code generation, but yes GraphQL complained after schema got generated, so here intention was to even fail generation during the code generation.

**Comment by lgandecki** [comment]
alright lets do this

**Comment by lgandecki** [comment]
shoot, it failed on master, could you guys please try to take a look and fix? :)

**Comment by Bhavesh-Suvalaka** [comment]
@lgandecki please take a look at this PR https://github.com/xolvio/chimp/pull/787 for fix

**Pull request merged**
