### PR TITLE
Hooks errors fix for #687

### PR DESCRIPTION
**Pull request by rsshilli**
This fixes a few things:
- Now an error in the hook will cause the tests to fail properly
- It seems the apostrophe in the GitHub slogan has changed?  I had to modify it from ASCII hex 27 to UTF-8 hex 2019 to get the tests to pass.
- I updated the text in 2 of the tests that didn't make sense and removed an index.js that looked bogus.

### CODE REVIEW

**Comment by rsshilli** [comment]
Huh.  The tests on Firefox failed because "Error: Failed to decode response from marionette".  I have no idea why that would happen.  Was that something I caused?

I'd retry the build but I'm not allowed.

**Comment by samhatoum** [comment]
Thank you for this. Chimp 1.0 has not moved to Chimpy:
https://github.com/TheBrainFamily/chimpy/pulls

**Comment by samhatoum** [comment]
Thank you for this. Chimp 1.0 has not moved to Chimpy:
https://github.com/TheBrainFamily/chimpy/pulls

**Comment by rsshilli** [comment]
Do you mean "now" moved to Chimpy? :-)

**Pull request closed without merging**
