### PR TITLE
Addition BrowserStack and SauceLabs session managers

### PR DESCRIPTION
**Pull request by dehamilton**
In reference to Issue #69, this pull request adds a session factory over the session manager and includes specific REST calls to close out sessions for BrowserStack and Sauce Labs.

### CODE REVIEW

**Comment by samhatoum** [comment]
This is awesome, thank you!

Can you please also provide some tests? This will make sure noone else (like us) messes up your code as we refactor and grow Chimp :)

**Comment by dehamilton** [comment]
Sure, I'll work on some tests. Anything specific you'd like to see or just good general coverage?

**Comment by samhatoum** [comment]
General good coverage. Have a look at session manager for reference. Should be very similar I think.

Thanks again!

**Comment by AGoliath** [comment]
I´ve played a bit with this branch and it worked very well with BrowserStack for the most part, thanks for that!

i did notice a little odd thing, though: I specify my remote connection via
--host=hub.browserstack.com --user=browserstackName--key=browserStackKey --name=browserStacktestname

and then needed to additionaly specify --port=80. Otherwise some random port would be selected and the connection to browserstack will fail with a Connection Refused.
@dehamilton  any ideas on that?

**Comment by ramijarrar** [comment]
@AGoliath That is the current chimp behaviour, not something that was added here.

**Comment by ramijarrar** [comment]
@samhatoum Is there anything still blocking this?

**Comment by samhatoum** [comment]
Yep, tests!

**Comment by samhatoum** [comment]
my bad, it's there. I missed it!

**Comment by ramijarrar** [comment]
:+1:

**Comment by opuzaman** [comment]
Hello, i am fairly new with chimp. can anyone tell me how to initiate a test with sauce labs?
Thanks

**Comment by samhatoum** [comment]
https://dash.readme.io/project/chimp/v1.0/docs/using-saucelabs-browserstack-seleniumgrid

**Comment by ramijarrar** [comment]
@samhatoum That's an internal link.

**Pull request merged**
